language: ruby
cache: bundler

rvm:
  - 2.0.0
before_install: gem install bundler -v 1.10.6
script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - akeem.oduola@andela.com
    on_failure: change
    on_success: never
